### ISSUE TITLE
Amar ujala epaper

### ISSUE THREAD

**Issue by therickyrick** [ParaSpl01t/amar-ujala-free-epaper#1]
Hi, I have found your project and very much impressed with it, can you also provide Dainik jagran code.

Actually I am new to GitHub and wanna do some coding if can help me with your project.
Also if pdf download option needs to be added in your current implementation.

Thanks I am available on rickyrick4everhere@gmail.com

**Comment by ParaSpl01t** [comment]
Hi, I do plan to provide amar ujala's pdf links in the upcoming update.
Dainik jagran uses some server side algorithm to append a random Integer to URL. Some example URLs are:

https://epaperapi.jagran.com/EpaperImages/14012021/Meerut/M-13mrt-pg1-0014734447.png
https://epaperapi.jagran.com/EpaperImages/14012021/Delhi/M-13del-pg1-0014853493.png
https://epaperapi.jagran.com/EpaperImages/14012021/Delhi/M-13del-pg7-0015211707.png

Notice the random letters near the end of URL, these may or may not be random. So, I won't be able to provide access to Dainik Jagran, Unless someone can figure out the algorithm used by them.

**Comment by therickyrick** [comment]
I will surely try to figure it out for random generation of integers.

But can I help you in coding for the pdf link option of Amarujala.

It will surely boost my confidence as an novice in this platform if you
will permit me to do so.

Thanks and Cheers

**Comment by ParaSpl01t** [comment]
you can fork the repo and make necessary changes. You can also use a library for pdf generation if you want.

**Comment by therickyrick** [comment]
Hi,

I hope you are in good health and peace.
I and hundreds of my relatives and friends enjoyed the amarujala epaper
from your repo url.

But suddenly from last 2 weeks the link is expired or not able to pull any
data.
Upon analysis I found the base url is no longer available.

It would be extremely helpful if you can troubleshoot and fix the same in
your leisure time.

I would be obliged and will love to provide you with any kind of technical
help required.

Thanks

**Comment by ParaSpl01t** [comment]
I looked into the issue, turns out not only did the changed the base url but the new base url will only work for amar ujala official domain only. 

As of now I have no fix for this but I'll keep looking for alternate ways.

**Comment by ParaSpl01t** [comment]
![image](https://github.com/user-attachments/assets/ec888a4a-3dc1-4ba4-9567-a7616f39b5f8)

If someone can figure out how these signature works than maybe there's a chance.

**Comment by therickyrick** [comment]
Hi,

Can we setup an session together sometimes to understand the requirement
over teams/zoom.

Let me know what you think.

Thanks

**Comment by ParaSpl01t** [comment]
I'm sorry for the late reply. been busy with some projects. 
For now, Please refer to #2 .
Thank you
